### ISSUE TITLE
GPU requirements and training time

### ISSUE THREAD

**Issue by dongfengxijian** [SHI-Labs/Semi-Supervised-Transfer-Learning#7]
How many GPUs and how long I need to train the framework? Thanks

**Comment by Walleclipse** [comment]
Hi,
The default CIFAR-10 experiments need ~5.3 GB GPU memory, and the default CUB-200 experiments need ~26.3 GB GPU memory (because of the bigger model and bigger image size).  For the experiments, two Tesla V100 G cards are enough. 
For training from the pre-trained model, the experiments only take ~3 hours. But for training from scratch, it may take more than 10 hours to get better results.

**Comment by dongfengxijian** [comment]
@Walleclipse Thank you for your replying！
